
version: '3'

services:

  backend:
    image: python:3.7-alpine
    command: sh -c "pip install flask && flask run"
    volumes:
    - ./backend.py:/backend.py
    environment:
      - FLASK_APP=backend
      - FLASK_DEBUG=true
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=0.0.0.0

  nginx:
    image: nginx:alpine
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - ./certs/nginx:/etc/nginx/ssl/self/
     - ./certs/root-ca/cert.pem:/etc/nginx/ssl/ca/cert.pem
    ports:
      - "8443:443"
